In [1]:
#checking version of pandas and numpy installed
import numpy
print(numpy.version.version)# numpy version
import pandas as pd
print(pd.__version__)# pandas version

1.19.2
1.1.3


In [2]:
#program to print hello HCIA PDTP-Huawei Team
print("Hello HCIA PDTP-Huawei Team")

Hello HCIA PDTP-Huawei Team


In [3]:
#program to define two variales,calculate their sum and display the results
x=40
y=50
print(x+y)

90


In [5]:
# tuple that contains one element
tuple1 = ("oranges")
print(tuple1)

oranges


In [8]:
#define a tuple then use for loop to print all the elements
tuple2 = ("oranges","apples","bananas","grapes")
for i in tuple2:
    print(i)

oranges
apples
bananas
grapes


In [9]:
# python dictionary
dict1 = {"name":"Reagan","phone":"+254722 222333"}
print(dict1)

{'name': 'Reagan', 'phone': '+254722 222333'}


In [10]:
#function to do multiplication
def mul(x,y):
    product=x*y
    return(product)
mul(8,6)

48

In [12]:
# function to return square
def sqrProd(x,y):
    sqrProd=(x*y)*(y*x)
    return(sqrProd)
sqrProd(2,5)

100

In [17]:
import numpy as np
# 5x5 array whose elements are zeros
array1 = np.zeros((5,5))
print(array1)
#3x3 matrix with values ranging from 0 to 8
array2 = np.arange(9).reshape(3, 3)
print(array2)
# find indices of non zero elements from[1,2,0,0,4,0]
array3 = np.array([1,2,0,0,4,0])
print(np.nonzero(array3))
#create a 10x10 array with random values and find the minimun and maximum values
array4 = np.random.rand(10,10)
print(array4)
print(np.min(array4))
print(np.max(array4))
# create a random vector of size 30 and find the mean value
array5 = np.random.rand(30)
print(array5)
print(np.mean(array5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4], dtype=int32),)
[[0.24770606 0.83480318 0.28434404 0.8270962  0.74089618 0.96845163
  0.11919103 0.33886542 0.78056962 0.76668051]
 [0.32798195 0.70061616 0.61532079 0.92827124 0.7127641  0.11730928
  0.01231963 0.00825814 0.75539676 0.17001766]
 [0.87601196 0.07429596 0.54322831 0.98666446 0.2220175  0.78731092
  0.45737964 0.71963551 0.91260841 0.07479218]
 [0.32565553 0.43872509 0.54844436 0.77157962 0.44916566 0.7621523
  0.51080619 0.5351558  0.05083215 0.05813402]
 [0.03462344 0.30691939 0.63274032 0.84797503 0.9293258  0.14839616
  0.29298201 0.87415932 0.29133034 0.50561709]
 [0.06207711 0.6866961  0.28619532 0.00515911 0.70863724 0.95155032
  0.18173377 0.61818612 0.015578   0.56018383]
 [0.8569717  0.53623708 0.33132929 0.48723561 0.60331252 0.92330131
  0.92534851 0.55445279 0.78585916 0.44559381]
 [0.77530889 0.27458801 0.89487842 0.4343550

In [20]:
# Prompt the user for two numbers
x = int(input("Enter the first number: "))
y = int(input("Enter the second number: "))

# Calculate the product
product = x * y

# Print the product with an appropriate label
print(product)

Enter the first number: 50
Enter the second number: 40
2000


In [24]:
# double list
def doubleList(numberList):
    for i in numberList:
        double= i *2 
        print(double)
numberList = [3,1,5]    
doubleList(numberList)

6
2
10
